function setSeverList(obj){$('#sever_list').val('');$('#sever_list option').show();if($("#a_list").val()){$('#sever_list option[a_rel!='+$("#a_list").val()+']').hide();var objs=$('#sever_list option[a_rel='+$("#a_list").val()+']');$('#w_list option').hide();$.each(objs,function(n,v){var w_v=$(v).attr('w_rel');$('#w_list option[value='+w_v+']').show();});}else{$('#w_list option').show();}
if($("#w_list").val()){$('#sever_list option[w_rel!='+$("#w_list").val()+']').hide();}}
function minQuantity(min,id){var id_str=id?"_"+id:'';var c_num=$("#c_num"+id_str).val();var n_value=$("#p_num"+id_str).val();if(n_value<=min){return false;}
var nn_val=Number(n_value)-Number(c_num);$("#p_num"+id_str).val(nn_val);getChangeData(id);}
function setNumberValue(number,id){var id_str=id?"_"+id:'';$("#p_num"+id_str).val(number);getChangeData(id);}
function checkQuantityInput(min,max,id){var id_str=id?"_"+id:'';var n_value=Number($("#p_num"+id_str).val());if(n_value<=min){n_value=min;}
if(n_value>=max){n_value=min;}
$("#p_num"+id_str).val(n_value);getChangeData(id);}
function addQuantity(max,id){var id_str=id?"_"+id:'';var c_num=Number($("#c_num"+id_str).val());var n_value=Number($("#p_num"+id_str).val());if(n_value>=max){alert("Can not max than "+n_value);return false;}
var nn_val=Number(n_value)+Number(c_num);$("#p_num"+id_str).val(nn_val);getChangeData(id);}
function setPorduct(obj){var jobj=$(obj);var server_id=jobj.val();if(server_id){var get_url="/getSeverData";$("#product_content").html('<div class="gold-box-quantity"><div class="product_img_small"><div class="menu_loading"></div></div></div>');$.get(get_url,{sid:server_id},function(data){$("#product_content").html(data);});}}
function getChangeData(id){if(id){var url="/getBasePro";var p_num=$("#p_num_"+id).val();var params={p_id:id,p_num:p_num};$("#price_"+id).html("Loading...");$.post(url,params,function(data){$("#price_"+id).html(data);});}else{var url="/getGoldPro";var server_id=$("#server_id").val();var p_num=$("#p_num").val();var params={server_id:server_id,p_num:p_num};$("#save_span").html("");$("#price_span").html("<div class=\'loading\'></div>");$("#amount").html("<div class=\'loading\'></div>");$("#avg_amount").html("<div class=\'loading\'></div>");$.post(url,params,function(data){$("#price_span").html(data.price);$("#save_span").html(data.save);$("#amount").html(data.amount);$("#avg_amount").html(data.avg_amount);},"json");}}
function deleteCart(key,price){var url="/order/Remove";$.post(url,{key:key,type:'ajax'},function(data){if(data==1){$("#c_"+key).remove();var n_price=$("#top_cart_total_price").html();var n_number=$("#cart_number").html();n_number=Number(n_number)-1;n_price=Number(n_price)-Number(price);n_price=n_price.toFixed(2);$("#top_cart_total_price").html(n_price);$("#cart_number").html(n_number);$("#cart_number_m").html(n_number);}else{altert("Delete Faild");}});}
function showLan(){$('#user_form').hide();$('#seach_form').hide();$('#shop_cart').hide();$('#shop_currency').hide();$('#web_lan').toggle();}
function showMobileLan(){$('#web_mobile_lan').toggle();}
function showCurrency(){$('#user_form').hide();$('#seach_form').hide();$('#shop_cart').hide();$('#web_lan').hide();$('#shop_currency').toggle();}
function showShoppingcart(){var cart_num=$("#cart_number").html();cart_num=Number(cart_num);if(cart_num>=5){var top_price=$("#cart_total_price");var top_action=$("#action_cart");$("#shop_cart").prepend(top_price);$("#shop_cart").prepend(top_action);}
$('#user_form').hide();$('#seach_form').hide();$('#shop_currency').hide();$('#web_lan').hide();$('#shop_cart').toggle();}
function showUser(){$('#shop_cart').hide();$('#seach_form').hide();$('#shop_currency').hide();$('#web_lan').hide();$('#user_form').toggle();}
function showSearch(){$('#shop_cart').hide();$('#user_form').hide();$('#shop_currency').hide();$('#web_lan').hide();$('#seach_form').toggle();}
function showTopMenu(obj){if($(obj).attr('rel')=='hide'){$("#top_menu_pc").show();$("#top_games").attr('rel','show');$("#top_games").addClass('top_games_down');}else{$("#top_menu_pc").hide();$("#top_games").attr('rel','hide');$("#top_games").removeClass('top_games_down');}}
function setMenuSearch(Key){var url="/site/getMenu";$("#top_main_menus").html("<div class='menu_loading'></div>");$.post(url,{key:Key,type:'ajax'},function(data){$("#top_main_menus").html(data);});}
function setMenuActive(obj){var jObj=$(obj);jObj.parent().find('.active').removeClass('active');jObj.addClass('active');}
function setCurrecy(obj){var jobj=$(obj).attr('value');window.location.href="/site/setPayType?type="+jobj;}
function showCmenu(obj){$(".c_menu").find("ul ul").hide();$(obj).find("ul").show();}
function setProduct(obj,game){var form_obj=$(obj).parent().parent();if(!game){var server_obj=form_obj.find('[name=server]');var server_id=server_obj.val();}else{var server_id='';}
var game_obj=form_obj.find('[name=game]');var game_id=game_obj.val();var num=form_obj.find('[name=p_num]').val();var url="/getChangeProduct";form_obj.parent().parent().find('.price_num').addClass('loading');$.get(url,{'server_id':server_id,'game_id':game_id,'num':num},function(data){form_obj.parent().parent().html(data);});}
function ShowMenu(obj){var jObj=$(obj);var pobj=jObj.parent().parent();var rel=jObj.attr('rel');if(rel=='All'){pobj.find("li.c_menu").slideDown();}else{pobj.find('li.c_menu').fadeOut();pobj.find('li.'+rel).fadeIn();}}
function buyProduct(cobj){var obj=$(cobj);var formData=obj.parents("form").serialize();var action=obj.attr('rel');var url="/order/addCart";$("#shop_cart").show();var c_number=$("#cart_number").html();c_number=Number(c_number);if(c_number>=9){alert('Max add 9 items!');var top_price=$("#cart_total_price");var top_action=$("#action_cart");$("#shop_cart").prepend(top_price);$("#shop_cart").prepend(top_action);return false;}
$.post(url,formData,function(data){if(action=='buy'){window.location.href="/order/cart";}else{var m_value=parseInt($("#cart_number_m").html())+1;$("#cart_number").html(m_value);$("#cart_number_m").html(m_value);$("#cart_empty").hide();$("#shop_cart").prepend(data.str);var n_price=$('#top_cart_total_price').html();var t_price=Number(n_price)+Number(data.price);t_price=t_price.toFixed(2);$('#top_cart_total_price').html(t_price);if(c_number>=5){var top_price=$("#cart_total_price");var top_action=$("#action_cart");$("#shop_cart").prepend(top_price);$("#shop_cart").prepend(top_action);}}},'json');}
jQuery.bt.options.closeWhenOthersOpen=true;function showItemsDetail(obj){var pid=$(obj).attr('rel_id');var item_id=$(obj).attr('rel');if(typeof(item_id)!='undefined'){var geturl='/showItemDetail?item_id='+item_id+'&p_id='+pid;}else{var geturl='/showItemDetail?p_id='+pid;}
$(obj).bt({positions:'right',width:260,height:290,cssStyles:{color:'#A38D6D'},cornerRadius:5,ajaxPath:geturl,fill:'#1a1b1b',strokeStyle:'#302e2e',spikeLength:10,spikeGirth:10,padding:8,strokeWidth:2}).btOn();}
function changeType(){$("#search_form").submit();}
function setNum(obj){var par_obj=$(obj).parent().parent().parent().parent().parent();par_obj.find('input[name=goods_num]').val($(obj).val());var un_price=$(obj).attr('rel-price');var price=$(obj).val()*un_price*$(obj).find("option:selected").attr('rel');par_obj.find('.rel_price').html(price.toFixed(2));}
jQuery(document).ready(function(){jQuery('.m_nav').meanmenu();});$(function(){$(window).scroll(function(){$("#top_menu_pc").hide();$("#top_games").attr('rel','hide');$("#top_games").removeClass('top_games_down');if($(window).scrollTop()>=100){$('.actGotop').fadeIn(300);}else{$('.actGotop').fadeOut(300);}});$('#nav').click(function(){$('html,body').animate({scrollTop:'0px'},800);});});$(function(){if($("#top_go").length>0){$(function(){$("#goPageTop").on("click",function(){$('body,html').animate({scrollTop:0},1000);return false;});});}});$(document).ready(function(){$("#tag_area").find('a').click(function(){if($($(this).attr("href")).length>0){var height=$($(this).attr("href")).offset().top-140;}else{var ahref=$(this).attr("href");var nhref=ahref.replace('#','');var height=$("a[name='"+nhref+"']").offset().top-140;}
if(height>0){$("html, body").animate({scrollTop:height+"px"},{duration:500,easing:"swing"});}
return false;});$("#tag_area_img").find('a').click(function(){if($($(this).attr("href")).length>0){var height=$($(this).attr("href")).offset().top-140;}else{var ahref=$(this).attr("href");var nhref=ahref.replace('#','');var height=$("a[name='"+nhref+"']").offset().top-140;}
if(height>0){$("html, body").animate({scrollTop:height+"px"},{duration:500,easing:"swing"});}
return false;});$(".news-content").find('em').find('a').click(function(){if($($(this).attr("href")).length>0){var height=$($(this).attr("href")).offset().top-140;}else{var ahref=$(this).attr("href");var nhref=ahref.replace('#','');var height=$("a[name='"+nhref+"']").offset().top-140;}
if(height>0){$("html, body").animate({scrollTop:height+"px"},{duration:500,easing:"swing"});}
return false;});$("#content_areas").find('a').click(function(){if($($(this).attr("href")).length>0){var height=$($(this).attr("href")).offset().top-140;}else{var ahref=$(this).attr("href");var nhref=ahref.replace('#','');var height=$("a[name='"+nhref+"']").offset().top-140;}
if(height>0){$("html, body").animate({scrollTop:height+"px"},{duration:500,easing:"swing"});}
return false;});});if(window.location.href.indexOf('#')>=0){if($(window.location.hash).length>0){$('html,body').animate({scrollTop:($(window.location.hash).offset().top-140)+"px"},300);}};function setindexProduct(obj){$('.lndex_hot_games').hide();$('.index-img-menu').find('li.current').removeClass('current');$(obj).parent().addClass("current");var s_id=$(obj).attr('rel');$("#"+s_id).show();}
$(document).ready(function(){$(".mr_frbox").slide({titCell:"",mainCell:".mr_frUl ul",autoPage:true,effect:"leftLoop",autoPlay:false,vis:4});$(".mr_zhe_hover").css("top",$('.mr_zhe').eq(0).height());$("li").mouseout(function(e){if((e.pageX<$(this).offset().left||e.pageX>($(this).offset().left+$(this).width()))||(e.pageY<$(this).offset().top||e.pageY>($(this).offset().top+$(this).height()))){$(this).find('.mr_zhe_i').show();$(this).find('.mr_zhe_hover').hide().stop().animate({top:'190px'},{queue:false,duration:190});return false;}});$('.mr_zhe').mouseover(function(event){$(this).find('.mr_zhe_i').hide();$(this).find('.mr_zhe_hover').show().stop().animate({top:'90px'},{queue:false,duration:190});return false;});});function changeLevel(obj){var jobj=$(obj);var sVal=Number($("#start_level").val());var eVal=Number($("#end_level").val());if(eVal<=sVal){alert("Start level is not greater than end level!");jobj.focus();}else{getAjaxVal(sVal,eVal);}}
function getAjaxVal(slevel,elevel){var game_id=$("#game_id").val();var server_id=$("#sever_list").val();var sub_id=$("#sub_id").val();var url="getPowerLevelPrice";var slevel=slevel?slevel:Number($("#start_level").val());var elevel=elevel?elevel:Number($("#end_level").val());var params={s_level:slevel,e_level:elevel,gid:game_id,server_id:server_id,sub_id:sub_id};$("#show_hour").html("<div class=\'loading\'></div>");$("#show_price").html("<div class=\'loading\'></div>");$.post(url,params,function(data){$("#show_hour").html(data.hour);$("#show_price").html(data.price);},"json");}
$(document).ready(function(){classes=$("#zone-list-img div.Top").map(function(){return $(this).attr("class").split(' ');});var classList=distinctList(classes);var tagList='<ul id="zone-tag-list"></ul>';tagItem='<li><a href="#" class="active">All</a></li>';$.each(classList,function(index,value){var value=value.replace("-"," ");if(value!='Top'&&value!='card'&&value!='p_category'&&value!='col_4'){tagItem+='<li><a href="#">'+value+'</a></li>';}});$("#zone-list-img").before($(tagList).append(tagItem));$('#zone-tag-list li a').on('click',function(e){var getText=$(this).text().replace(" ","-");if(getText=='All'){$("#zone-list-img div.Top").slideDown();}else{$("#zone-list-img div.Top").fadeOut();$("#zone-list-img div."+getText).fadeIn();}
$('#zone-tag-list li a').removeClass('active');$(this).addClass('active');e.preventDefault();});});function distinctList(inputArray){var i;var length=inputArray.length;var outputArray=[];var temp={};for(i=0;i<length;i++){temp[inputArray[i]]=0;}
for(i in temp){outputArray.push(i);}
return outputArray;}
$('[name="payment"]').change(function(){var elem=$(this);$("#payment_mothed").find('.active').removeClass('active');elem.parent().addClass('active');checkPayment();});function checkPayment(){var method=$("input[name='payment']:checked").val();var coupon=$("#coupon").val();var currency=$("#currency_tag").val();var params={method:method,coupon:coupon,currency:currency}
var url="/order/setPayment";$("#payment_price_data").html('<div class="menu_loading"></div>');$.post(url,params,function(data){if(data){$("#payment_price_data").html(data);}});}
function showProductPro(key){$("#pro_"+key).toggle();}
function setCurrecyAjax(obj){var currency=$(obj).val();var url="/site/setPayType";$.get(url,{currency:currency},function(data){if(data){checkPayment();}});}
function showPassWord(obj){if($(obj).is(':checked')){var email=$("#mail").val();var url="/order/checkEmail";$.get(url,{email:email},function(data){if(data==1){$("#create-account").css('visibility','visible');$("#register_say").html("<font color=red>Please input your password and confirm the password!</font>");}else{$(obj).attr("checked",false);$("#register_say").html("<font color=red>"+email+" was already registered!</font>");}});}else{$("#create-account").css('visibility','hidden');}}
function checkForm(){var check=true;$.each($(".flowfVerify"),function(i,n){var str=$(n).val();var verify=$(n).attr("rel-verify");switch(verify){case 'required':if(str==""){$(n).focus();check=false;return false;}
break;}
if($("#is_account").attr("checked")=='checked'){if($("#passwd1").val()==''){$("#error").html("<font color='red'> Password must be enter.</font>");check=false;$("#passwd1").focus();return false;}
if($("#passwd2").val()==''){$("#error").html("<font color='red'> Confirm Password must be enter.</font>");check=false;$("#passwd2").focus();return false;}
if($("#passwd2").val()!=$("#passwd1").val()){$("#error").html("<font color='red'>The password and confirmation password do not match .</font>");check=false;$("#passwd1").focus();return false;}}});$("#check-buttom").attr('value','Loading..');return check;}
function checkCoupon(){var url="/order/checkCoupon";var n_val=$("#coupon_discount").html();var n_final=$("#final-price").html();if($("#coupon").val()!=""){checkPayment();}else{alert("Coupon Code Can Not Be Null!!");}}
function showHidePayment(){if($("#other_payment").attr('rel')=='hide'){$("#more_payment_tag").addClass('more_payment_active');$("#other_payment_content").show();$("#other_payment").attr('rel','show');}else{$("#more_payment_tag").removeClass('more_payment_active');$("#other_payment_content").hide();$("#other_payment").attr('rel','hide');}}
function setCurrencyServer(obj){var server=$(obj).attr('rel');$(obj).parent().find('.active').removeClass('active');$(obj).addClass('active');$("#server").val(server);getCurrency();}
function setCurrency(obj){var trade_id=$(obj).attr('rel');$(obj).parent().find('.active').removeClass('active');$(obj).addClass('active');$("#trade_id").val(trade_id);getCurrency();}
function getCurrency(){var trade_id=$("#trade_id").val();var server=$("#server").val();var params={trade_id:trade_id,server:server};var url="/site/getCurrencyWay";$("#exchange_mothed").html('<div class="menu_loading"></div>');$.post(url,params,function(data){if(data){$("#exchange_mothed").html(data);}});}
function showFastDetail(obj,postion){postion=postion?postion:'left';$(obj).bt({positions:postion,width:260,height:290,contentSelector:"$(this).next().html()",cssStyles:{color:'#A38D6D'},cornerRadius:5,fill:'#302e2e',strokeStyle:'#333',spikeLength:10,spikeGirth:10,padding:10,strokeWidth:2}).btOn();}
$('.item_content').find('img').bt({positions:'top',width:260,height:290,contentSelector:"$(this).next().html()",cssStyles:{color:'#A38D6D'},cornerRadius:5,fill:'#302e2e',strokeStyle:'#333',spikeLength:10,spikeGirth:10,padding:10,strokeWidth:2}).btOn();jQuery(document).ready(function(){jQuery('.skillbar').each(function(){jQuery(this).find('.skillbar-bar').animate({width:jQuery(this).attr('data-percent')},6000);});});function checkVoteMaxSelect(){var user_id=$("#use_id").val();var type=$("#poll_type").val();var select_max=$("#select_max").val();if(!user_id){alert('Pls log in or register to be ffxiv4gil members to vote!');}
var selectLen=$("input[name='PollVote[choice_id][]']:checked").length;if(type==2){if(select_max){if(selectLen==select_max){var notSelect=$("input:checkbox").not("input:checked");$.each(notSelect,function(n,o){$(o).attr('disabled',true);});}else{var notSelect=$("input:checkbox").not("input:checked");$.each(notSelect,function(n,o){$(o).attr('disabled',false);});}}}}
function checkFormSubmit(){var select_min=$("#select_min").val();var type=$("#poll_type").val();var vselectLen=$("input[name='PollVote[choice_id][]']:checked").length;if(type==2&&select_min){if(vselectLen<select_min){alert('Less Select '+select_min+'！');return false;}}
$('#poll-form').submit();}